server {
    listen 5000;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    location ~ ^/.+/(assets/.+)$ {
        try_files /$1 =404;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
